//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scotec.T4Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scotec.T4Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%imports%&gt;
        ///
        ///namespace &lt;%namespace%&gt;
        ///{
        ///	public sealed partial class &lt;%classname%&gt; : &lt;%baseclassname%&gt;
        ///	{
        ///&lt;%fields%&gt;
        ///
        ///		public &lt;%classname%&gt;(string endOfLine&lt;%parameters%&gt;) : base(endOfLine)
        ///		{
        ///&lt;%fieldinitializations%&gt;
        ///		}
        ///		
        ///		protected override void Generate()
        ///		{
        ///&lt;%implementation%&gt;
        ///		}
        ///
        ///&lt;%features%&gt;
        ///&lt;%includes%&gt;
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string CSCodeTemplate {
            get {
                return ResourceManager.GetString("CSCodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		private void &lt;%templatename%&gt;TemplateMethod( &lt;%parameters%&gt;)
        ///		{
        ///&lt;%include%&gt;
        ///		}.
        /// </summary>
        internal static string CSIncludeTemplate {
            get {
                return ResourceManager.GetString("CSIncludeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%imports%&gt;
        ///
        ///Namespace &lt;%namespace%&gt;
        ///
        ///	Public NotInheritable Partial Class &lt;%classname%&gt;
        ///		Inherits &lt;%baseclassname%&gt;
        ///
        ///&lt;%fields%&gt;
        ///
        ///		Public Sub New(ByVal endOfLine as String&lt;%parameters%&gt;)
        ///			MyBase.New(endOfLine)
        ///&lt;%fieldinitializations%&gt;
        ///		End Sub
        ///		
        ///		Protected Overrides Sub Generate()
        ///&lt;%implementation%&gt;
        ///		End Sub
        ///
        ///&lt;%features%&gt;
        ///&lt;%includes%&gt;
        ///
        ///	End Class
        ///
        ///End Namespace.
        /// </summary>
        internal static string VBCodeTemplate {
            get {
                return ResourceManager.GetString("VBCodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		Private Sub &lt;%templatename%&gt;TemplateMethod( &lt;%parameters%&gt;)
        ///&lt;%include%&gt;
        ///		End Sub.
        /// </summary>
        internal static string VBIncludeTemplate {
            get {
                return ResourceManager.GetString("VBIncludeTemplate", resourceCulture);
            }
        }
    }
}
